pub_site/src/pub_site/api/cheque/__init__.py
# coding=utf-8
from ..utils import SubBlueprint
from .. import api_mod

cheque_mod = SubBlueprint('cheque', api_mod, '/cheque')


from . import views

pub_site/src/pub_site/api/cheque/views.py
# coding=utf-8
from __future__ import unicode_literals
from flask import request, render_template, jsonify
from flask.ext.login import current_user
from . import cheque_mod as mod
from pub_site import pay_client
from pub_site.auth.utils import login_required
from decimal import Decimal
from .. import response


@mod.route('/draw', methods=['POST'])
@login_required
def draw():
    data = request.values
    params = {
        'amount': Decimal(data['amount']),
        'info': data['info'],
        'valid_seconds': 60*60,
        'cheque_type': 'INSTANT'
    }

    user_id = current_user.user_id

    result = pay_client.app_draw_cheque(user_id, params=params)
    if result is not None:
        return response.success(result)
    return response.failed('draw cheque failed.')


@mod.route('/cash', methods=['POST'])
@login_required
def cash():
    pass


@mod.route('/list', methods=['GET'])
@login_required
def list_cheques():
    user_id = current_user.user_id
    result = pay_client.app_list_cheque(user_id)

    return response.success(result['cheques'])

pub_site/src/pub_site/cheque/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint, g, request

cheque_mod = Blueprint('cheque', __name__, static_folder='static')

from . import views


@cheque_mod.before_request
def set_current_channel():
    g.current_channel = 'cheque'
    endpoint = request.endpoint.split('.')[1]
    g.current_cheque_tab = endpoint

pub_site/src/pub_site/cheque/views.py
# coding=utf-8
from __future__ import unicode_literals
from flask import render_template
from . import cheque_mod as mod
from pub_site.auth.utils import login_required


@mod.route('/', methods=['GET'], defaults={'path': ''})
@mod.route('/<path:path>', methods=['GET'])
@login_required
def index(path):
    return render_template('cheque/index.html')

pub_site/src/pub_site/templates/cheque/base.html
{% extends 'layout.html' %}
{% block title %}支票{% endblock %}

{% block content %}
    <div class="contRight payoffRight firstRight">
        {% include 'message.html' %}
        <div>
            <h2 class="first">账户信息</h2>
            <div class="line firstline margin48">
                <label class="widthauto">可用余额</label>
                <span id="available_balance" class="money">{{ available_balance }}</span>&nbsp;元
            </div>
        </div>

        <div id="tx_list" data-api-url="{{ url_for('main.list_transactions') }}">
            <div class="tabtit margin48 clearfix">
                <ul id="cheque_tabs">
                    <li id="draw_cheque" class="{{ 'cur' if g.current_cheque_tab == 'draw' else '' }}">
                        <a href="{{ url_for('cheque.draw') }}">开支票</a>
                    </li>
                    <li id="cash_cheque" class="{{ 'cur' if g.current_cheque_tab == 'cash' else '' }}">
                        <a href="{{ url_for('cheque.cash') }}">兑现支票</a>
                    </li>
                    <li id="list_cheque" class="{{ 'cur' if g.current_cheque_tab == 'list_cheques' else '' }}">
                        <a href="{{ url_for('cheque.list_cheques') }}">支票列表</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="tablock margin48 tablockcur">
            {% block cheque_content %}
                <h1>{{ g.current_cheque_tab }}</h1>
            {% endblock %}
        </div>
  </div>
{% endblock %}

pub_site/src/pub_site/templates/cheque/cash.html
{% extends 'cheque/base.html' %}

{% block cheque_content %}
    {{ super() }}
{% endblock %}

pub_site/src/pub_site/templates/cheque/draw.html
{% extends 'cheque/base.html' %}

{% block cheque_content %}
    {{ super() }}
{% endblock %}

pub_site/src/pub_site/templates/cheque/index.html
{% extends 'layout.html' %}
{% block title %}支票{% endblock %}

{% block content %}
    <div class="contRight payoffRight firstRight">
        {% include 'message.html' %}
        <div id="app-cheque"></div>
        <script src="{{ url_for('static', filename='compo/cheque.js') }}"></script>
    </div>
{% endblock %}

pub_site/src/pub_site/templates/cheque/list.html
{% extends 'cheque/base.html' %}

{% block cheque_content %}
    {{ super() }}
{% endblock %}