pub_site/src/pub_site/checkout/__init__.py
# coding=utf-8
from __future__ import unicode_literals

from flask import Blueprint, render_template

checkout_entry_mod = Blueprint('checkout_entry', __name__)


from . import views, zyt_views

pub_site/src/pub_site/checkout/views.py
# coding=utf-8
from __future__ import unicode_literals

from flask import render_template, Response, jsonify, request, url_for, redirect
from . import checkout_entry_mod as mod
from .constant import REQUEST_CLIENT_PAYMENT_SCENE_MAPPING
from .constant import RequestClientType
from pub_site.checkout.commons import payment_failed, generate_submit_form
from pytoolbox.util.log import get_logger
from pytoolbox.util import urls
from pub_site.utils.entry_auth import pay_limit_referrer
from pub_site.utils import req
from pub_site import config, pay_client
from .utils import get_template


logger = get_logger(__name__)


@mod.route('/<sn>/result', methods=['GET'])
def pay_result(sn):
    """支付结果
    BAD, EXPIRED, INVALID, ERROR,
    DONE, CREATED
    """
    result = pay_client.get_payment_result(sn)
    if not pay_client.is_success_result(result):
        if result is None:
            res = 'BAD'
        elif result.status_code == 413:
            # 过期
            res = 'EXPIRED'
        elif result.status_code == 404:
            # 找不到
            res = 'INVALID'
        else:
            res = 'ERROR'
        return jsonify(res=res)
    state = result.data['state']
    res = 'CREATED'
    if state != 'CREATED':
        res = 'DONE'
    return jsonify(res=res)


@mod.route('/<sn>/callback', methods=['GET'])
def pay_callback(sn):
    """支付结果web回调
    """
    data = pay_client.get_payment_result(sn)
    result = ""
    if not pay_client.is_success_result(data):
        return payment_failed(result)
    state = data.data['state']
    if state != 'CREATED':
        result = 'SUCCESS'

    # pure sn.
    sn = data.data['sn']
    return pay_client.web_payment_callback(sn, result)


@mod.route('/<sn>', methods=['GET'])
def checkout(sn):
    """支付收银台入口"""
    client_type = req.client_type()
    payment_scene = REQUEST_CLIENT_PAYMENT_SCENE_MAPPING[client_type]

    result = pay_client.get_payment_info(sn, payment_scene)
    if not pay_client.is_success_result(result):
        return payment_failed(result)
    info = result.data['info']
    if info['state'] != 'CREATED':
        return render_template(get_template("checkout/info", client_type), msg="该订单已支付, 如失败，请重新请求支付")

    vases = result.data['activated_evas']
    vas_infos = result.data['vas_infos']

    # 页面适配
    if len(vases) == 1:
        template = "checkout/one_type_checkout.html"
    else:
        template = get_template("checkout/checkout", client_type)

    is_in_weixin = client_type == RequestClientType.WEIXIN
    return render_template(template, sn=sn, info=info, vases=vases, vas_infos=vas_infos, client_type=client_type,
                           activated_vas=request.args.get('activated_vas'),
                           is_in_weixin=is_in_weixin)


@mod.route("/pay/<sn>/<vas_name>", methods=["GET"])
@pay_limit_referrer(config.Checkout.VALID_NETLOCS)
def pay(sn, vas_name):
    """支付入口, 限制只能从checkout过来"""
    if request.args.get('x') is not None or vas_name.startswith('_') or vas_name[0].isdigit() or sn.isupper():
        # FIXME: 自动判断sn和vas_name
        vas_name, sn = sn, vas_name

    extra_params = {k: v for k, v in request.args.items()} or None
    client_type = req.client_type()
    payment_scene = REQUEST_CLIENT_PAYMENT_SCENE_MAPPING[client_type]
    return do_pay(sn, vas_name, payment_scene, extra_params=extra_params, client_type=client_type)


def do_pay(sn, vas_name, payment_scene, extra_params=None, client_type=None):
    from .constant import WeixinPayType

    result = pay_client.get_payment_param(sn, payment_scene, vas_name, extra_params)
    if not pay_client.is_success_result(result):
        return payment_failed(result, client_type=client_type)

    # echo back vas_name, and payment_type.
    vas_name = result.data['vas_name']
    payment_type = result.data['payment_type']
    params = result.data['params']
    if vas_name == 'ALI_PAY':
        if client_type == RequestClientType.WEIXIN:
            return render_template(get_template("checkout/info", client_type), go_back=True, msg="请在浏览器或支付宝中打开使用支付宝支付。")
        url = params['_url']
        return Response(generate_submit_form(url, params, keep_all=True, excludes={'_url'}))
    elif vas_name == 'WEIXIN_PAY':
        if payment_type == WeixinPayType.NATIVE:
            code_url = params['code_url']
            info = params['_info']
            return render_template("checkout/wx_pay_native.html", code_url=code_url, info=info, sn=sn)
        elif payment_type == WeixinPayType.JSAPI:
            if client_type != RequestClientType.WEIXIN:
                return render_template(get_template("checkout/info", client_type), go_back=True, msg="请在微信中打开使用微信支付。")
            if '_url' in params:
                import urllib
                url = params['_url']
                # FIXME: sn, vas_name exchange
                dest_url = config.HOST_URL + url_for('checkout_entry.pay', sn=vas_name, vas_name=sn, x='')
                redirect_uri = urls.build_url(config.Checkout.WEIXIN_AUTH_REDIRECT_URI, dest_url=dest_url)
                url = url % (urllib.urlencode({'x': redirect_uri})[2:],)
                return redirect(url)
            return render_template("checkout/wx_pay_jsapi.html", params=params, sn=sn)
    elif vas_name == 'LIANLIAN_PAY':
        url = params['_url']
        return Response(generate_submit_form(url, params))
    elif vas_name == 'TEST_PAY':
        url = params['_url']
        return Response(generate_submit_form(url, params))
    elif vas_name == 'ZYT':
        # 自游通余额支付
        url = params['_url']
        params['_sn'] = sn
        return Response(generate_submit_form(url, params, keep_all=True))
    return render_template(get_template("checkout/info", client_type), go_back=True, msg="支付方式错误")

pub_site/src/pub_site/templates/checkout/checkout.html
{% extends "checkout/layout.html" %}

{% block title %}绿野支付{% endblock %}
{% block css %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/showLoading.css') }}" rel="stylesheet">
{% endblock %}
{% block js %}
    <script src="{{ url_for('static', filename='js/jquery-1.8.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery/jquery.showLoading.js') }}"></script>
    <script src="{{ url_for('static', filename='js/browser_utils.js') }}"></script>
{% endblock %}

{% block main %}
    <div class="wxpayTit clearfix">
        <div class="wxpayL">
            <h3>订单编号：<span>{{ info.order_id }}</span></h3>
            <h3>商品名称：<span>{{ info.name|truncate(45, True) }}</span></h3>
            <h3>商品描述：<span>{{ info.desc|truncate(45, True) }}</span></h3>
            <h3>交易流水：<span>{{ info.sn }}</span></h3>
        </div>
        <div class="wxpayR">
            金额: <span>{{ info.amount }}</span>元
        </div>
    </div>
    <div class="wxCont">
        <ul class="">
            {% for vas_name in vases %}
            {% set vas_info = vas_infos[vas_name] %}
                <li class="zf_list1 samezf" id="{{ vas_name }}">
                    <div class="bankChoice">
                        <input id="i_{{ vas_name }}" type="radio" value="{{ vas_name }}" {% if loop.first %}checked{% endif %} name="zf" class="onlychice">
                        <label>{{ vas_info.name }}</label>
                        <img src="{{ url_for('static', filename='images/checkout/%s.png' % vas_name) }}" width="42" height="42" >
                        <span class="worn">{{ vas_info.desc }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <button id="bt_pay_now" class="nowpay" value="{{ vases[0] }}">立即支付</button>
        <span hidden=true id="pay_result" class="pay_result_before"></span>
    </div>
{% endblock %}


{#{% block layer %}#}
{#    <!--S遮罩层-->#}
{#    <div class="bgLayer"></div>#}
{#    <!--E遮罩层-->#}
{#    <div class="payfinishLayer">#}
{#        <a href="###" class="close"></a>#}
{#        <p class="tit">请新开的页面完成支付</p>#}
{#        <div class="payLine">如已经成功支付，请点击<button>已完成付款</button></div>#}
{#        <div class="payLine2">如付款遇到问题，您可以<button>重新支付</button></div>#}
{#    </div>#}
{#{% endblock %}#}

{% block scripts -%}
    <script>
        $(function() {
            /*选择支付方式*/
            $("li.zf_list1.samezf").click(function(){
                var r = $('#i_' + this.id)[0];
                r.click();
            });

            function disable_pay_bt(msg) {
                var pay_result = $('#pay_result')[0];
                pay_result.setAttribute("class", "pay_result")
                pay_result.hidden = false;
                pay_result.innerText = msg;
                $('#bt_pay_now').off('click');
                $('#bt_pay_now').click(function(){
                    alert(msg);
                });
            }


{#            /*支付完成弹层*/#}
{#            // close#}
{#            $(".payfinishLayer a.close").click(function(){#}
{#                $(".payfinishLayer,.bgLayer").fadeOut();#}
{#            });#}
{##}
{#            // retry#}
{#            $(".payfinishLayer .payLine2 button").click(function(){#}
{#                $(".payfinishLayer,.bgLayer").fadeOut();#}
{#            });#}
{##}
{#            // finish#}
{#            $(".payfinishLayer .payLine button").click(function(){#}
{#                $.getJSON('{{ url_for('checkout_entry.pay_result', sn=sn) }}')#}
{#                        .done(function (data) {#}
{#                            var res = data.res;#}
{#                            if (res == 'SUCCESS') {#}
{#                                var msg = "支付成功，请关闭该页面";#}
{#                                disable_pay_bt(msg);#}
{#                            } else if (res == 'FAILED') {#}
{#                                alert("支付未成功，请重新支付");#}
{#                            } else if (res == 'EXPIRED') {#}
{#                                var msg = "本支付链接过期，请关闭页面，重新请求支付";#}
{#                                alert(msg);#}
{#                                disable_pay_bt(msg);#}
{#                            } else if (res == 'INVALID') {#}
{#                                var msg = "交易号错误或者已失效，请关闭页面，请重新发起支付";#}
{#                                alert(msg);#}
{#                                disable_pay_bt(msg);#}
{#                            } else {#}
{#                                alert("请求异常");#}
{#                            }#}
{#                        }).complete(function(){#}
{#                            $(".payfinishLayer,.bgLayer").fadeOut();#}
{#                        });#}
{#            });#}

            $("#bt_pay_now").click(function(){
                var vas_name = $('input[type=radio][name=zf]:checked')[0].value;
                jQuery('body').showLoading({
                    'afterShow': function() {
                        $.getJSON('{{ url_for('checkout_entry.pay_result', sn=sn) }}')
                                .done(function (data) {
                                    var res = data.res;
                                    if (res != 'CREATED') {
                                        jQuery('body').hideLoading();
                                    }
                                    if (res == 'DONE') {
                                        var msg = "已支付完成，请关闭该页面, 如果失败，请重新发起支付";
                                        disable_pay_bt(msg);
                                    } else if (res == 'CREATED') {
                                        {#                                $(".payfinishLayer,.bgLayer").fadeIn();#}
                                        var url = "{{ CONFIG.HOST_URL + url_for('checkout_entry.pay', sn=sn, vas_name='') }}" + vas_name;
                                        navigateToUrl(url);
                                        if (is_safari) {
                                            jQuery('body').hideLoading();
                                        };
                                    } else if (res == 'EXPIRED') {
                                        var msg = "本支付链接过期，请关闭页面，重新请求支付";
                                        alert(msg);
                                        disable_pay_bt(msg);
                                    } else if (res == 'INVALID') {
                                        var msg = "交易号错误或者已失效，请关闭页面，请重新发起支付";
                                        alert(msg);
                                        disable_pay_bt(msg);
                                    } else {
                                        alert("请求异常");
                                    }
                                })
                                .fail(function () {
                                    alert("请求异常");
                                    jQuery('body').hideLoading();
                                });
                }});
            });
        })

    </script>
{%- endblock %}

pub_site/src/pub_site/templates/checkout/checkout_mobile.html
{% extends "checkout/layout_mobile.html" %}

{% block title %}绿野支付{% endblock %}

{% block css %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/showLoading.css') }}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/jquery-1.8.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery/jquery.showLoading.js') }}"></script>
    <script src="{{ url_for('static', filename='js/browser_utils.js') }}"></script>
{% endblock %}

{% block body_start %}
    <img hidden="hidden" src="{{ url_for('static', filename='images/checkout/lvye_logo_360.png') }}">
{% endblock %}

{% block main %}
    <div class="pay-info">
        <h3>订单编号: <span>{{ info.order_id }}</span></h3>
        <h3>商品名称: <span>{{ info.name|truncate(24, True) }}</span></h3>
        <h3>订单金额: <span>{{ info.amount }}</span>元</h3>
        <hr>
    </div>
    {% for vas_name in vases %}
        {% set vas_info = vas_infos[vas_name] %}
        <div class="pay-list" id="{{ vas_name }}">
            <div class="pay-item-select">
                <input id="i_{{ vas_name }}" type="radio" value="{{ vas_name }}" {% if loop.first %}checked{% endif %} name="zf" class="onlychice">
            </div>
            <div class="pay-item">
                <img src="{{ url_for('static', filename='images/checkout/%s.png' % vas_name) }}" width="42" height="42" >
            </div>
            <div class="pay-content">
                <h2 class="pay-title">{{ vas_info.name }}</h2>
                <p class="pay-desc">
                    {{ vas_info.desc }}
                </p>
            </div>
        </div>
    {% endfor %}
    <button id="bt_pay_now" class="nowpay" value="{{ vases[0] }}">立即支付</button>
    <div class="pay_result_row"><span hidden=true id="pay_result" class="pay_result_before"></span></div>
{% endblock %}

{% block scripts %}
<script>
    $(function() {
        {% if activated_vas %}
            var r = $('#i_{{ activated_vas }}')[0];
            r.click();
        {% endif %}

        /*选择支付方式*/
        $("div.pay-list").click(function(){
            var r = $('#i_' + this.id)[0];
            r.click();
        });

        function disable_pay_bt(msg) {
            var pay_result = $('#pay_result')[0];
            pay_result.setAttribute("class", "pay_result")
            pay_result.hidden = false;
            pay_result.innerText = msg;
            $('#bt_pay_now').off('click');
            $('#bt_pay_now').click(function(){
                alert(msg);
            });
        }

        $("#bt_pay_now").click(function(){
            var vas_name = $('input[type=radio][name=zf]:checked')[0].value;
            jQuery('body').showLoading({
                'afterShow': function() {
                    $.getJSON('{{ url_for('checkout_entry.pay_result', sn=sn) }}')
                            .done(function (data) {
                                var res = data.res;
                                if (res != 'CREATED') {
                                    jQuery('body').hideLoading();
                                }
                                if (res == 'DONE') {
                                    var msg = "已支付完成，请关闭该页面, 如果失败，请重新发起支付";
                                    disable_pay_bt(msg);
                                } else if (res == 'CREATED') {
                                    {#                                $(".payfinishLayer,.bgLayer").fadeIn();#}
                                    var url = "{{ CONFIG.HOST_URL + url_for('checkout_entry.pay', sn=sn, vas_name='') }}" + vas_name;
                                    navigateToUrl(url);
                                    if (is_safari) {
                                        jQuery('body').hideLoading();
                                    };
                                } else if (res == 'EXPIRED') {
                                    var msg = "本支付链接过期，请关闭页面，重新请求支付";
                                    alert(msg);
                                    disable_pay_bt(msg);
                                } else if (res == 'INVALID') {
                                    var msg = "交易号错误或者已失效，请关闭页面，请重新发起支付";
                                    alert(msg);
                                    disable_pay_bt(msg);
                                } else {
                                    alert("请求异常");
                                }
                            })
                            .fail(function () {
                                alert("请求异常");
                                jQuery('body').hideLoading();
                            });
                }});
        });
    })
</script>
{% endblock %}

pub_site/src/pub_site/templates/checkout/info.html
{% extends "checkout/layout.html" %}

{% block title %}提示{% endblock %}

{% block main %}
    <div class="wxCont">
        <div class="contRight payoffRight firstRight">
            <h3>{{ msg }}</h3>
            {% if go_back %}
                <button class="nowpay" onclick="window.history.go(-1);">返回</button>
            {% endif %}
        </div>
    </div>
{% endblock %}

pub_site/src/pub_site/templates/checkout/info_mobile.html
{% extends "checkout/layout_mobile.html" %}

{% block title %}提示{% endblock %}

{% block main %}
    <h3 class="msg">{{ msg }}</h3>
    {% if go_back %}
        <button class="nowpay" onclick="window.history.go(-1);">返回</button>
    {% endif %}
{% endblock %}

pub_site/src/pub_site/templates/checkout/layout_mobile.html
<!DOCTYPE html>
{% block all %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width,user-scalable=0">
    <meta name="keyword" content="绿野,绿野户外,绿野旅行,绿野滑雪">
    <meta name="description" content="绿野支付方便您完成在绿野平台的各种交易">
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=no">

    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
        <link href="{{ url_for('static', filename='css/checkout_mobile.css') }}" rel="stylesheet">
    {% endblock %}
    <!--[if lte IE 9]>
    <script src="{{ url_for('static',filename='js/html5.js') }}"></script>
    <![endif]-->
    {% block js %}
    {% endblock %}

    <!--[if lte IE 9]>
    <script src="{{ url_for('static',filename='js/html5.js') }}"></script>
    <![endif]-->
</head>

<body>
{% block body_start %}
{% endblock %}
<div class="wrap">
    <header class="header">
        <div class="logo">
            <a href="http://www.lvye.com" target="_blank">
                <img src="{{ url_for('static', filename='images/logo_zyt.jpg') }}" height="34" width="192" title="首页" alt="首页">
            </a>
        </div>
    </header>

    <div class="body">
        {% block main %}
        {% endblock %}
    </div>
    <footer>
        <hr>
        <p class="grayColor copyright">
        © 1999-2015 <a href="http://www.lvye.com">www.lvye.com</a> 绿野户外网版权所有
        </p>
    </footer>
</div>

<script>
    var csrftoken = $('meta[name=csrf-token]').attr('content');
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% block scripts %}
{% endblock %}
</body>
</html>
{% endblock %}

pub_site/src/pub_site/templates/checkout/one_type_checkout.html
<!DOCTYPE>
<html>
<head>
    <script src="{{ url_for('static', filename='js/browser_utils.js') }}"></script>
</head>
<body></body>
<script>
    var url = "{{ CONFIG.HOST_URL + url_for('checkout_entry.pay', sn=sn, vas_name=vases[0]) }}";
    navigateToUrl(url);
</script>
</html>

pub_site/src/pub_site/templates/checkout/wx_info.html
{% extends "checkout/layout.html" %}

{% block title %}提示{% endblock %}

{% block main %}
    <div class="wxCont">
        <div class="contRight payoffRight firstRight">
            <h3>{{ msg }}</h3>
            {% if go_back %}
                <button class="nowpay" onclick="window.history.go(-1);">返回</button>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        window.location.href = "weixin://";
        setTimeout(function(){
            window.location.href="http://itunes.apple.com/us/app/wechat!/id414478124?mt=8";
        } , 1500);
    </script>
{% endblock %}

pub_site/src/pub_site/templates/checkout/wx_info_mobile.html
{% extends "checkout/layout_mobile.html" %}

{% block title %}提示{% endblock %}

{% block main %}
    <h3 class="msg">{{ msg }}</h3>
    {% if go_back %}
        <button class="nowpay" onclick="window.history.go(-1);">返回</button>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script>
        window.location.href = "weixin://";
        setTimeout(function(){
            window.location.href="http://itunes.apple.com/us/app/wechat!/id414478124?mt=8";
        } , 1500);
    </script>
{% endblock %}

pub_site/src/pub_site/templates/checkout/wx_pay_jsapi.html
<!DOCTYPE>
<html>
<head>
    <title>微信JSAPI支付</title>
</head>
<body></body>
<script>
    function onBridgeReady() {
        WeixinJSBridge.invoke(
                'getBrandWCPayRequest',
                {
                    "appId": "{{ params.appId }}",     //公众号名称，由商户传入
                    "timeStamp": "{{ params.timeStamp }}",         //时间戳，自1970年以来的秒数
                    "nonceStr": "{{ params.nonceStr }}", //随机串
                    "package": "{{ params.package }}",
                    "signType": "{{ params.signType }}",         //微信签名方式：
                    "paySign": "{{ params.paySign }}" //微信签名
                },
                function(res){
                    if (res.err_msg == "get_brand_wcpay_request:ok" ) {
                        window.location.href = '{{ CONFIG.HOST_URL + url_for('checkout_entry.pay_callback', sn=sn) }}';
                    } else if (res.err_msg == "get_brand_wcpay_request:cancel") {
                        window.history.back();
                    } else if (res.err_msg == "get_brand_wcpay_request:fail") {
                        window.history.back();
                    }
                    // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回    ok，但并不保证它绝对可靠。
                }
        );
    }

    if (typeof WeixinJSBridge == "undefined"){
        if( document.addEventListener ){
            document.addEventListener('WeixinJSBridgeReady', onBridgeReady, false);
        }else if (document.attachEvent){
            document.attachEvent('WeixinJSBridgeReady', onBridgeReady);
            document.attachEvent('onWeixinJSBridgeReady', onBridgeReady);
        }
    }else{
        onBridgeReady();
    }
</script>
</html>

pub_site/src/pub_site/templates/checkout/wx_pay_native.html
{% extends "checkout/layout.html" %}

{% block css %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/showLoading.css') }}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/jquery-1.8.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery/jquery.showLoading.js') }}"></script>
{% endblock %}

{% block title %}微信扫码支付{% endblock %}

{% block main %}
    <div class="wxpayTit clearfix">
        <div class="wxpayL">
            <h3>订单编号：<span>{{ info.order_id }}</span></h3>
            <h3>商品名称：<span>{{ info.name|truncate(45, True) }}</span></h3>
        </div>
        <div class="wxpayX">
            金额: <span>{{ info.amount }}</span>元
        </div>
    </div>
    <div class="wxCont">
        <h3><img style="display: inline;" src="{{ url_for('static', filename='images/checkout/wxpay_logo.png') }}" height="30" title="微信支付" alt="微信支付">微信支付
            <span hidden=true id="pay_result" class="pay_result"></span>
        </h3>
        <p class="ewm">
            <img src="{{ qrcode(code_url) }}" width="260" height="260" alt="二维码">
            <img src="{{ url_for('static', filename='images/checkout/wxpay_desc.png') }}" title="操作指示" alt="操作指示">
        </p>
        <img src="{{ url_for('static', filename='images/checkout/wxPay_guide.jpg') }}" width="381" height="417" alt="" >
    </div>
{% endblock %}


{% block scripts -%}
    <script>
        $(function(){
            var req_pay_result = setInterval(function(){
                $.getJSON('{{ url_for('checkout_entry.pay_result', sn=sn) }}')
                        .done(function (data) {
                            var res = data.res;
                            if (res == 'DONE') {
                                clearInterval(req_pay_result);

                                var msg = "已支付完成，请关闭该页面, 如果失败，请重新发起支付";
                                var pay_result = $('#pay_result')[0];
                                pay_result.hidden = false;
                                pay_result.innerText = msg;
                                // 回调通知
                                jQuery('body').showLoading({
                                    'afterShow': function() {
                                        setTimeout(function () {
                                            window.open('{{ CONFIG.HOST_URL + url_for('checkout_entry.pay_callback', sn=sn) }}', '_self')
                                        }, 300);
                                }});
                            }
                        });
            }, 1500);
        })
    </script>
{%- endblock %}

pub_site/src/pub_site/templates/checkout/zyt_pay_web.html
{% extends "checkout/layout.html" %}

{% block css %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/showLoading.css') }}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/jquery/jquery-1.11.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery/jquery.showLoading.js') }}"></script>
    <script src="{{ url_for('static', filename='js/verification-code.js') }}"></script>
{% endblock %}

{% block title %}自由通余额支付{% endblock %}

{% block main %}
    <div class="wxpayTit clearfix">
        <div class="wxpayL">
            <h3>订单编号：<span>{{ info.order_id }}</span></h3>
            <h3>商品名称：<span>{{ info.name|truncate(45, True) }}</span></h3>
        </div>
        <div class="wxpayX">
            金额: <span>{{ info.amount }}</span>元
        </div>
    </div>
    <div class="wxCont">
    <div class="contRight payoffRight firstRight">
        <div class="line firstline margin48">
            <label class="widthauto">可用余额</label>
            <span id="available_balance" class="money" >{{ balance }}</span>&nbsp;元
        </div>
        <form class="zyt_pay" method="post" action="">
            {{ form.csrf_token }}
            {% from 'forms.html' import input, verification_code_and_submit, submit %}
            {{ verification_code_and_submit(form) }}
        </form>
    </div>
    </div>
{% endblock %}