admin_site/src/admin_site/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, print_function, division

import os
from flask import Flask

import flask.ext.login as flask_login
from pytoolbox.util.flask_extras.utils import ReverseProxied

login_manager = flask_login.LoginManager()


def _init_template(app):
    @app.context_processor
    def register_context():
        return dict()

    app.jinja_options['extensions'].append('jinja2.ext.loopcontrols')


def _register_mods(app):
    from admin_site.reconciliation import recon_mod

    app.register_blueprint(recon_mod, url_prefix='/recon')


def create_app(env='dev', deploy=False):
    if deploy:
        return Flask(__name__)

    from pytoolbox.util import pmc_config
    from admin_site import config

    app = Flask(__name__, template_folder='./templates')

    env = env or 'dev'
    os.environ['ENV'] = env
    pmc_config.register_config(config, env=env)
    app.config.from_object(config.App)

    _register_mods(app)
    _init_template(app)
    login_manager.init_app(app)

    # reverse proxied
    app.wsgi_app = ReverseProxied(app.wsgi_app)
    return app

admin_site/src/admin_site/config/__init__.py
# coding=utf-8
import os


HOST_URL = 'http://admin.pay.lvye.com'

class App:
    SECRET_KEY = os.environ.get('SECRET_KEY') or '.yek eyvl'
    PROPAGATE_EXCEPTIONS = True
    TESTING = False
    DEBUG = True
    LOGIN_DISABLED = False
    WTF_CSRF_SECRET_KEY = 'a random string'


class Host:
    API_SITE = 'http://dev_pay.lvye.com:5100'

admin_site/src/admin_site/reconciliation/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


recon_mod = Blueprint('reconciliation', __name__, static_folder='static')

from . import views

admin_site/src/admin_site/reconciliation/views.py
# -*- coding: utf-8 -*-
from . import recon_mod as mod
from flask import request, render_template, url_for, redirect
from flask.ext.login import login_required, UserMixin, login_user, logout_user, current_user
from admin_site import login_manager
from admin_site import config

users = {
    'yl': {'pw': 'lvye'},
    'op': {'pw': 'lvye123'}
}


class User(UserMixin):
    pass


@login_manager.user_loader
def user_loader(email):
    if email not in users:
        return

    user = User()
    user.id = email
    return user


@login_manager.request_loader
def request_loader(request):
    email = request.form.get('email')
    if email not in users:
        return

    user = User()
    user.id = email

    # DO NOT ever store passwords in plaintext and always compare password
    # hashes using constant-time comparison!
    user.is_authenticated = request.form['pw'] == users[email]['pw']

    return user


@mod.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('reconciliation/login.html')
    username = request.form['username']
    if request.form['pw'] == users.get(username, {}).get('pw'):
        user = User()
        user.id = username
        login_user(user)
        return redirect(config.HOST_URL + url_for('reconciliation.list_reconciliation'))

    return render_template('reconciliation/login.html', tips=u"用户名或者密码错误")


@mod.route('/protected')
@login_required
def protected():
    return 'Logged in as: ' + current_user.id


@mod.route('/logout')
def logout():
    logout_user()
    return 'Logged out'


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(config.HOST_URL + url_for('reconciliation.login'))


@mod.route('/', methods=['GET'])
@login_required
def list_reconciliation():
    return render_template('reconciliation/list.html', config=_get_config())


@mod.route('/search', methods=['GET'])
@login_required
def search_transaction():
    return render_template('reconciliation/search.html', config=_get_config())


def _get_config():
    return compose_conf(
        apiHost=config.Host.API_SITE
    )


def compose_conf(**kwargs):
    conf = {}
    for key, value in kwargs.iteritems():
        key = key.encode('ascii')
        value = value.encode('ascii')
        conf[key] = value

    return conf

admin_site/src/admin_site/templates/layout.html
<!DOCTYPE>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{% block title %}{% endblock %}</title>

{% block css %}
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/showLoading.css') }}" rel="stylesheet">
    {% block inline_css %}
    {% endblock %}
{% endblock %}


<!--[if lt IE 9]>
<script src="{{ url_for('static',filename='js/html5.js') }}"></script>
<![endif]-->
<script src="{{ url_for('static', filename='js/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery/jquery.showLoading.js') }}"></script>
{% block js %}{% endblock %}

</head>

<body>


<header>
	<div class="hdCont clearfix">
    	<h1 class="logo">
			<a href="http://www.lvye.cn" target="_blank">
				<img src="http://www.lvye.cn/header/images/logo.png" class="pngfix" height="47" width="103" title="首页" alt="首页">
			</a>
		</h1>
        <div class="loginBtn clearfix">
        	<div class="sx">
                <span class="emailBtn"></span>
                <ul class="sEmail" style="display:none">
                    <li><a href="###" target="_blank" title="">我的消息</a></li>
                    <li><a class="warn" href="###" target="_blank" title="">我的提醒(10)</a></li>
                    <em></em>
                </ul>
            </div>
            <div class="yh">
                <a class="userName" href="/">{{ current_user.user_name }}<em></em></a>
                <ul class="userexit" style="display:none">
                    <li><a href="{{ url_for('auth.logout') }}" title="">退出</a></li>
                    <em></em>
                </ul>
            </div>

        </div>
    </div>
</header>

{% block popup %}{% endblock %}

<footer>
	<div class="ftCont clearfix">
    	<ul class="cL">
        	<li><a href="###" target="_blank">关于我们</a></li>
            <li><a href="###" target="_blank">帮助中心</a></li>
        </ul>
        <p class="cR">Copyright  1999-2014  www.lvye.cn  绿野户外网版权所有</p>
    </div>
</footer>



{% block scripts %}
    <script>
        $(function () {
            $(".loginBtn .sx").hover(function () {
                $(this).find("ul").stop().fadeIn();
            }, function () {
                $(this).find("ul").stop().fadeOut();
            });
            $(".loginBtn .yh").click(function () {
                $(this).find("ul").stop().fadeIn();
            });
            var csrftoken = $('meta[name=csrf-token]').attr('content');
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
    </script>
    {% block inline_scripts %}
    {% endblock %}
{% endblock %}

</body>
</html>

admin_site/src/admin_site/templates/reconciliation/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="{{ url_for('static', filename='js/angular.min.js') }}"></script>
	<script>
	angular.module("global-config", []);
	angular.module('global-config').value('globalConfig', {{ config | safe }});
	</script>

	<script src="{{ url_for('static', filename='js/debitnote.js') }}"></script>
	<link href="{{ url_for('static',filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
	<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static',filename='bootstrap/js/bootstrap.min.js') }}"></script>
	{% block header %}{% endblock %}
    <title></title>
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <a class="brand" href="/recon" style="padding: 5px 20px;"><img src="http://img01.lvye.com.cn/lvyehuodong/static/huodong/images/logo.png"></a>
    </div>
	<a class="btn btn-success" href="{{ url_for('reconciliation.list_reconciliation') }}" role="button">对账结果查看</a>
	<a class="btn btn-success" href="{{ url_for('reconciliation.search_transaction') }}" role="button">交易记录查询</a>
  </div>
</nav>


{% block content %}{% endblock %}


</body>
</html>

admin_site/src/admin_site/templates/reconciliation/list.html
{% extends "reconciliation/base.html" %}
{% block header %}
<script src="{{ url_for('static', filename='js/debitnote/ctrl.js') }}"></script>
{% endblock %}

{% block content %}



<div ng-app="debitnote" ng-controller="debitnoteCtrl"> 

<div>最后对账时间：  <label ng-bind="datestr.date"></label></div>

<div>不一致记录共：  <label ng-bind="num"></label> 条</div>

<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>No</th>
      <th>SN</th>
      <th>绿野支付记录</th>
      <th></th>
      <th></th>
      <th></th>
      <th>第三方记录</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>交易时间</th>
      <th>绿野单号</th>
      <th>交易类型</th>
      <th>金额</th>
      <th>交易时间</th>
      <th>第三方支付单号</th>
      <th>第三方渠道</th>
      <th>交易类型</th>
      <th>金额</th>
    </tr>
  </thead>
  <tr ng-repeat="item in datas" class="danger">
  <td>[[$index]]</td>
  <td>[[item.sn]]</td>
  <td>[[item.ly_date]]</td>
  <td>[[item.ly_orderid]]</td>
  <td>[[item.ly_type]]</td>
  <td>[[item.ly_amount]]</td>
  <td>[[item.ll_date]]</td>
  <td>[[item.ll_orderid]]</td>
  <td>[[item.ll_vasname]]</td>
  <td>[[item.ll_type]]</td>
  <td>[[item.ll_amount]]</td>
  </tr>
<table>
</div>

{% endblock %}

admin_site/src/admin_site/templates/reconciliation/login.html
{% extends "reconciliation/base.html" %}
{% block header %}
{% endblock %}

{% block content %}

{{ tips }}
<form  action="{{ url_for('reconciliation.login') }}" method="post">
  <div class="form-group">
    <label for="username">用户名：</label>
    <input type="text" class="form-control" id="username" name="username"  placeholder="用户名">
  </div>
  <div class="form-group">
    <label for="pw">Password</label>
    <input type="password" class="form-control" id="pw" name="pw" placeholder="密码">
  </div>
  <button type="submit" class="btn btn-default">登录</button>
</form>



{% endblock %}

admin_site/src/admin_site/templates/reconciliation/search.html
{% extends "reconciliation/base.html" %}
{% block header %}
<script src="{{ url_for('static', filename='js/debitnote/searchCtrl.js') }}"></script>
{% endblock %}

{% block content %}


<div ng-app="debitnote" ng-controller="searchCtrl"> 
<form class="form-inline" action="">
  <div class="form-group">
    <label for="orderid">按订单号:</label>
    <input type="text" class="form-control" name="orderid" id="orderid" placeholder="订单号">
  </div>
  <input type="submit" class="btn btn-primary"/>
</form>

<br>

<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>创建时间</th>
      <th>发起人</th>
      <th>对方</th>
      <th>操作</th>
      <th>订单号</th>
      <th>交易金额（元）</th>
      <th>状态</th>
      <th>交易名称</th>
      <th>详情</th>
    </tr>
  </thead>
  <tr ng-repeat="item in tx">
  <td>[[item.created_on]]</td>
  <td>[[item.payee]]</td>
  <td>[[item.payer]]</td>
  <td>[[item.type]]</td>
  <td>[[item.orderid]]</td>
  <td>[[item.amount]]</td>
  <td>[[item.state]]</td>
  <td>[[item.comments]]</td>
  <td><button ng-click="toggle([[item.tx_id]])" class="btn btn-info">明细详情</button></td>
  </tr>
</table>

<br>
<h2>交易明细</h2>
<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>时间</th>
      <th>前一状态</th>
      <th>目前状态</th>
      <th>第三方名称</th>
      <th>类型</th>
      <th>金额（元）</th>
      <th>事件ID</th>
    </tr>
  </thead>
  <tr ng-repeat="item in txd">
  <td>[[item.created_on]]</td>
  <td>[[item.prev_state]]</td>
  <td>[[item.state]]</td>
  <td>[[item.vas_name]]</td>
  <td>[[item.type]]</td>
  <td>[[item.amount]]</td>
  <td>[[item.event_id]]</td>
  <tr>
</table>

<br>
<h2>关联账户资金流转</h2>
<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>时间</th>
      <th>账户</th>
      <th>初始金额</th>
      <th>资金变动</th>
      <th>最终余额</th>
      <th>备注</th>
      <th>事件ID</th>
    </tr>
  </thead>
  <tr ng-repeat="item in ad">
  <td>[[item.created_on]]</td>
  <td>[[item.user_id]]</td>
  <td>[[item.balance1]]</td>
  <td>[[item.amount]]</td>
  <td>[[item.balance2]]</td>
  <td></td>
  <td>[[item.event_id]]</td>
  </tr>
</table>

<br>




</div>
</div>

{% endblock %}