pub_site/src/pub_site/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint, g

main_mod = Blueprint('main', __name__, static_folder='static')

from . import views


@main_mod.before_request
def set_current_channel():
    g.current_channel = 'main'

pub_site/src/pub_site/main/views.py
# coding=utf-8
from __future__ import unicode_literals
from flask import request, render_template, jsonify
from flask.ext.login import current_user
from . import main_mod as mod
from pub_site import pay_client
from .transaction import query_transactions
from pub_site.auth.utils import login_required


@mod.route('/main', methods=['GET'])
@login_required
def index():
    uid = current_user.user_id
    balance = pay_client.app_query_user_available_balance(uid)
    return render_template('main/index.html', available_balance='%.2f' % balance)


@mod.route('/transactions', methods=['GET'])
@login_required
def list_transactions():
    from .transaction import TX_VAS_MSG
    uid = current_user.user_id
    data = request.args
    role = data['role']
    page_no = int(data.get('page_no', 1))
    q = data.get('q', '').strip()
    q = q if q else None
    vas_name = data.get('vas_name')

    page_size = 10
    count, transactions = query_transactions(uid, role, page_no, page_size, vas_name, q)
    res = {
        'count': count,
        'page_no': page_no,
        'page_size': page_size,
        'page_count': (count - 1) / page_size + 1,
        'transactions': transactions,
        'vas_name': vas_name
    }
    return render_template('main/tx_list.html', res=res, vases=TX_VAS_MSG)


@mod.route('/available_balance', methods=['GET'])
@login_required
def available_balance():
    uid = current_user.user_id
    balance = pay_client.app_query_user_available_balance(uid)

    return jsonify(available_balance='%.2f' % balance)

pub_site/src/pub_site/templates/main/index.html
{% extends 'layout.html' %}
{% block title %}我的自游通{% endblock %}

{% block content %}
    <div class="contRight payoffRight firstRight">
        {% include 'message.html' %}
        <h2 class="first">账户信息</h2>
        <div class="line firstline margin48">
            <label class="widthauto">可用余额</label>
            <span id="available_balance" class="money" data-api-url="{{ url_for('main.available_balance') }}">{{ available_balance }}</span>&nbsp;元
        </div>
        <p class="tit margin48">交易记录</p>


        <div id="tx_list" data-api-url="{{ url_for('main.list_transactions') }}">
        </div>
  </div>
{% endblock %}

{% block inline_scripts %}
    <script src="{{ url_for('static', filename='js/transaction_list.js') }}"></script>
{% endblock %}

pub_site/src/pub_site/templates/main/macros.html
{% macro tx_list(txs, count, page_no, page_size, page_count) -%}
    <div class="tablock margin48 tablockcur">
        <table width="950" cellspacing="0" cellpadding="0" style="table-layout: fixed;overflow: auto; word-wrap: break-word;">
            <tr class="first">
                <td width="80" height="40" class="center">创建时间</td>
                <td width="70" class="center">类型</td>
                <td width="90" class="center">金额(元)</td>
                <td width="100" class="center">状态</td>
                <td width="200" class="center">交易名称</td>
                <td width="120" class="center">来源</td>
                <td width="100" class="center">交易号</td>
                <td width="80" class="center">支付方式</td>
                <td width="60" class="center">订单号</td>
            </tr>
            {% for tx in txs %}
                <tr>
                    <td width="80" height="60" class="center">{{ tx.created_on }}</td>
                    <td class="right">{{ tx.type }}</td>
                    {% if tx.is_failed %}
                        <td class="right grey">{{ "+%.2f"|format(tx.amount) }}</td>
                    {% elif tx.role in ['TO', 'TX_TO'] %}
                        {% if tx.is_created %}
                            <td class="right light_red">{{ "+%.2f"|format(tx.amount) }}</td>
                        {% else %}
                            <td class="right red">{{ "+%.2f"|format(tx.amount) }}</td>
                        {% endif %}
                    {% elif tx.role in ['FROM', 'TX_FROM'] %}
                        {% if tx.is_created %}
                            <td class="right light_green">{{ "-%.2f"|format(tx.amount) }}</td>
                        {% else %}
                            <td class="right green">{{ "-%.2f"|format(tx.amount) }}</td>
                        {% endif %}
                    {% else %}
                        <td class="right">{{ "%.2f"|format(tx.amount) }}</td>
                    {% endif %}
                    <td class="center">{{ tx.state }}</td>
                    <td class="center">{{ tx.comments }}</td>
                    <td class="center">{{ tx.channel }}</td>
                    <td class="center">{{ tx.sn }}</td>
                    <td class="center">{{ tx.vas }}</td>
                    <td height="40px" class="center">{{ tx.order_id }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <div id="tx_list_pager" class="page" data-page-no="{{ page_no }}" data-page-count="{{ page_count }}">
        <p class="suml">共 {{ count }} 条，每页 {{ page_size }} 条, 第 {{ page_no }}/{{ page_count }} 页</p>
        <p class="pageNum">
            <a id="tx_list_first" class="long" href="javascript:void(0)" title="">首页</a>
            <a id="tx_list_prev" class="long" href="javascript:void(0)" title="">上一页</a>
            <a id="tx_list_next" class="long" href="javascript:void(0)" title="">下一页</a>
            <a id="tx_list_last" class="long" href="javascript:void(0)" title="">末页</a>
        </p>
    </div>
{%- endmacro %}

pub_site/src/pub_site/templates/main/tx_list.html
<div class="tabtit margin48 clearfix">
    <ul id="tx_type_tabs" data-cur="#total_tx">
        <li id="total_tx" class="cur">全部</li><li id="in_tx">账户收款</li><li id="out_tx">账户付款</li><li id="tx_in_tx">交易收款</li><li id="tx_out_tx">交易付款</li>
    </ul>

    <div class="search">
        <label for="tx_search_vas">支付方式</label>
        <select id="tx_search_vas">
            {% for vas, name in vases.items() %}
                <option value="{{ vas }}" {% if vas == res.vas_name %}selected{% endif %}>{{ name }}</option>
            {% endfor %}
        </select>
        <input id="tx_search_q" type="text" placeholder="交易名称, 订单号" class="txk" />
        <button id="tx_search_bt">查找</button>
    </div>

</div>

{% if res.count > 0 %}
    {% from 'main/macros.html' import tx_list %}
    {{ tx_list(res.transactions, res.count, res.page_no, res.page_size, res.page_count) }}
{% else %}
    <p><h2>暂无任何记录!!</h2></p
{% endif %}